In [359]:
import pandas as pd
import numpy as np

In [360]:
df = pd.read_csv(r"C:\Users\DELL\Desktop\Kaggle\House Prices - Advanced Regression Techniques\train.csv")

In [361]:
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [362]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          91 non-null     object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     588 non-null    object
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1423 non-null   object
 31  BsmtCond       1423 non-null   object
 32  BsmtExposure   1422 non-null   object
 33  BsmtFinType1   1423 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    object
 58  GarageType     1379 non-null   object
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   object
 64  GarageCond     1379 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      object
 73  Fence          281 non-null    object
 74  MiscFeature    54 non-null     object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

In [363]:
df.describe()

,Id,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,...,WoodDeckSF,OpenPorchSF,EnclosedPorch,3SsnPorch,ScreenPorch,PoolArea,MiscVal,MoSold,YrSold,SalePrice
count,1460.000000,1460.000000,1201.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1452.000000,1460.000000,...,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000,1460.000000
mean,730.500000,56.897260,70.049958,10516.828082,6.099315,5.575342,1971.267808,1984.865753,103.685262,443.639726,...,94.244521,46.660274,21.954110,3.409589,15.060959,2.758904,43.489041,6.321918,2007.815753,180921.195890
std,421.610009,42.300571,24.284752,9981.264932,1.382997,1.112799,30.202904,20.645407,181.066207,456.098091,...,125.338794,66.256028,61.119149,29.317331,55.757415,40.177307,496.123024,2.703626,1.328095,79442.502883
min,1.000000,20.000000,21.000000,1300.000000,1.000000,1.000000,1872.000000,1950.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,2006.000000,34900.000000
25%,365.750000,20.000000,59.000000,7553.500000,5.000000,5.000000,1954.000000,1967.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,2007.000000,129975.000000
50%,730.500000,50.000000,69.000000,9478.500000,6.000000,5.000000,1973.000000,1994.000000,0.000000,383.500000,...,0.000000,25.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,2008.000000,163000.000000
75%,1095.250000,70.000000,80.000000,11601.500000,7.000000,6.000000,2000.000000,2004.000000,166.000000,712.250000,...,168.000000,68.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.000000,2009.000000,214000.000000
max,1460.000000,190.000000,313.000000,215245.000000,10.000000,9.000000,2010.000000,2010.000000,1600.000000,5644.000000,...,857.000000,547.000000,552.000000,508.000000,480.000000,738.000000,15500.000000,12.000000,2010.000000,755000.000000

In [364]:
df.drop('Id', axis = 1, inplace = True)

In [365]:
df.isna().sum()

MSSubClass          0
MSZoning            0
LotFrontage       259
LotArea             0
Street              0
Alley            1369
LotShape            0
LandContour         0
Utilities           0
LotConfig           0
LandSlope           0
Neighborhood        0
Condition1          0
Condition2          0
BldgType            0
HouseStyle          0
OverallQual         0
OverallCond         0
YearBuilt           0
YearRemodAdd        0
RoofStyle           0
RoofMatl            0
Exterior1st         0
Exterior2nd         0
MasVnrType        872
MasVnrArea          8
ExterQual           0
ExterCond           0
Foundation          0
BsmtQual           37
BsmtCond           37
BsmtExposure       38
BsmtFinType1       37
BsmtFinSF1          0
BsmtFinType2       38
BsmtFinSF2          0
BsmtUnfSF           0
TotalBsmtSF         0
Heating             0
HeatingQC           0
CentralAir          0
Electrical          1
1stFlrSF            0
2ndFlrSF            0
LowQualFinSF        0
GrLivArea           0
BsmtFullBath        0
BsmtHalfBath        0
FullBath            0
HalfBath            0
BedroomAbvGr        0
KitchenAbvGr        0
KitchenQual         0
TotRmsAbvGrd        0
Functional          0
Fireplaces          0
FireplaceQu       690
GarageType         81
GarageYrBlt        81
GarageFinish       81
GarageCars          0
GarageArea          0
GarageQual         81
GarageCond         81
PavedDrive          0
WoodDeckSF          0
OpenPorchSF         0
EnclosedPorch       0
3SsnPorch           0
ScreenPorch         0
PoolArea            0
PoolQC           1453
Fence            1179
MiscFeature      1406
MiscVal             0
MoSold              0
YrSold              0
SaleType            0
SaleCondition       0
SalePrice           0
dtype: int64

In [366]:
## Dropping the columns with the high correlation
corr_matrix = df.corr(numeric_only=True).abs()
upper = corr_matrix.where(
    np.triu(np.ones(corr_matrix.shape), k=1).astype(bool)
)

to_drop = [column for column in upper.columns if any(upper[column] > 0.8)]
df.drop(labels = to_drop, axis = 1, inplace = True)
df.head()

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [367]:
na_cols = [i for i in df.columns if df[i].isna().sum() > 0]
len(na_cols)

18

In [368]:
numerical_features = df.select_dtypes(exclude='object').drop('SalePrice',axis = 1).columns

In [369]:
len(numerical_features)

32

In [370]:
categorical_features = df.select_dtypes(include='object').columns
len(categorical_features)

43

In [371]:
## Defining dependent and independent variables
X = df.drop('SalePrice', axis = 1)
y = df['SalePrice']

In [372]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2, random_state=42)

In [373]:
## Binary columns and multi features
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder

binary_features = [col for col in categorical_features if df[col].nunique() == 2]
multi_features  = [col for col in categorical_features if df[col].nunique() > 2]

binary_encoder = OrdinalEncoder()
multi_encoder = OneHotEncoder(handle_unknown='ignore')

# preprocessor = ColumnTransformer(
#     transformers=[
#         ('binary', binary_encoder, binary_features),
#         ('multi', multi_encoder, multi_features)
#     ]
# )

In [374]:
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

num_pipe = Pipeline([
    ('mean_imputer', SimpleImputer(strategy='mean')),
    ('scaler', StandardScaler()),
])

cat_pipe = Pipeline([
        ('cat_imputer', SimpleImputer(strategy='most_frequent')),
])

cleaning_data = ColumnTransformer([
    ('numerical_features_optimization', num_pipe, numerical_features),
    ('categorical_features_optimization', cat_pipe, categorical_features),
])

In [375]:
cleaning_data.fit(X_train)
cols = [col.split("__")[-1] for col in cleaning_data.get_feature_names_out()]
X_train = pd.DataFrame(cleaning_data.transform(X_train),columns = cols)

In [376]:
X_train.head()

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,GarageType,GarageFinish,GarageQual,GarageCond,PavedDrive,PoolQC,Fence,MiscFeature,SaleType,SaleCondition
0,-0.866764,-0.015314,-0.212896,-0.820445,0.372217,-0.455469,-1.346063,-0.601531,1.037269,-0.285504,...,Attchd,RFn,TA,TA,Y,Ex,MnPrv,Shed,WD,Normal
1,0.07411,-0.505211,-0.265245,-0.088934,1.268609,0.718609,0.439214,-0.601531,-0.971996,-0.285504,...,Attchd,RFn,TA,TA,Y,Ex,MnPrv,Shed,WD,Normal
2,-0.631546,-0.148922,-0.177841,-0.820445,1.268609,-1.988293,-1.683818,-0.601531,-0.971996,-0.285504,...,Attchd,Unf,TA,TA,P,Ex,MnPrv,Shed,WD,Normal
3,-0.161109,-0.460675,-0.324474,-0.820445,1.268609,-1.107734,-1.683818,0.859229,0.267995,-0.285504,...,Detchd,Unf,TA,TA,Y,Ex,MnPrv,Shed,WD,Normal
4,-0.161109,-0.906036,-0.529035,-0.820445,0.372217,-1.531707,-1.683818,-0.601531,-0.49692,-0.285504,...,Detchd,Unf,TA,TA,Y,Ex,MnPrv,Shed,WD,Normal

In [377]:
len([i for i in X_train.columns if X_train[i].isna().sum()>0])

0

In [378]:
X_test = pd.DataFrame(cleaning_data.transform(X_test),columns= cols)
X_test.head()

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,GarageType,GarageFinish,GarageQual,GarageCond,PavedDrive,PoolQC,Fence,MiscFeature,SaleType,SaleCondition
0,-0.866764,-0.015314,-0.211594,-0.088934,2.165,-0.259789,0.87347,-0.601531,0.472844,-0.285504,...,Attchd,RFn,TA,TA,Y,Ex,MnPrv,Shed,WD,Normal
1,0.07411,1.231697,0.145643,1.374088,-0.524174,0.751222,0.487465,1.496862,1.276986,-0.285504,...,Attchd,RFn,TA,TA,Y,Ex,MnPrv,Shed,WD,Normal
2,-0.631546,-0.638819,-0.160826,-0.820445,0.372217,-1.433867,-1.683818,-0.601531,-0.971996,-0.285504,...,Detchd,Unf,TA,TA,Y,Ex,MnPrv,Shed,WD,Normal
3,-0.161109,-0.906036,-0.529035,-0.088934,1.268609,-0.781602,-1.683818,-0.601531,-0.102477,-0.285504,...,Detchd,Unf,TA,TA,Y,Ex,MnPrv,Shed,WD,Normal
4,-0.866764,0.830872,0.205338,2.105599,-0.524174,1.175195,1.114724,-0.195765,1.255193,-0.285504,...,Attchd,Fin,TA,TA,Y,Ex,MnPrv,Shed,WD,Normal

In [379]:
from sklearn.preprocessing import OrdinalEncoder
bin_cols = [i for i in X_train.columns if len(X_train[i].unique()) == 2]
label = OrdinalEncoder()
X_train_encoded = pd.DataFrame(label.fit_transform(X_train[bin_cols]), columns=label.get_feature_names_out())
X_train.drop(labels = bin_cols, axis = 1, inplace = True)
X_train = pd.concat([X_train, X_train_encoded],axis = 1)

In [380]:
X_train.head()

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,PavedDrive,PoolQC,Fence,MiscFeature,SaleType,SaleCondition,Street,Alley,Utilities,CentralAir
0,-0.866764,-0.015314,-0.212896,-0.820445,0.372217,-0.455469,-1.346063,-0.601531,1.037269,-0.285504,...,Y,Ex,MnPrv,Shed,WD,Normal,1.0,0.0,0.0,1.0
1,0.07411,-0.505211,-0.265245,-0.088934,1.268609,0.718609,0.439214,-0.601531,-0.971996,-0.285504,...,Y,Ex,MnPrv,Shed,WD,Normal,1.0,0.0,0.0,1.0
2,-0.631546,-0.148922,-0.177841,-0.820445,1.268609,-1.988293,-1.683818,-0.601531,-0.971996,-0.285504,...,P,Ex,MnPrv,Shed,WD,Normal,1.0,0.0,0.0,1.0
3,-0.161109,-0.460675,-0.324474,-0.820445,1.268609,-1.107734,-1.683818,0.859229,0.267995,-0.285504,...,Y,Ex,MnPrv,Shed,WD,Normal,1.0,0.0,0.0,1.0
4,-0.161109,-0.906036,-0.529035,-0.820445,0.372217,-1.531707,-1.683818,-0.601531,-0.49692,-0.285504,...,Y,Ex,MnPrv,Shed,WD,Normal,1.0,1.0,0.0,1.0

In [381]:
X_test_encoded = pd.DataFrame(label.transform(X_test[bin_cols]), columns=label.get_feature_names_out())
X_test.drop(labels = bin_cols, axis = 1, inplace = True)
X_test = pd.concat([X_test, X_test_encoded],axis = 1)
X_test.head()

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,PavedDrive,PoolQC,Fence,MiscFeature,SaleType,SaleCondition,Street,Alley,Utilities,CentralAir
0,-0.866764,-0.015314,-0.211594,-0.088934,2.165,-0.259789,0.87347,-0.601531,0.472844,-0.285504,...,Y,Ex,MnPrv,Shed,WD,Normal,1.0,0.0,0.0,1.0
1,0.07411,1.231697,0.145643,1.374088,-0.524174,0.751222,0.487465,1.496862,1.276986,-0.285504,...,Y,Ex,MnPrv,Shed,WD,Normal,1.0,0.0,0.0,1.0
2,-0.631546,-0.638819,-0.160826,-0.820445,0.372217,-1.433867,-1.683818,-0.601531,-0.971996,-0.285504,...,Y,Ex,MnPrv,Shed,WD,Normal,1.0,0.0,0.0,1.0
3,-0.161109,-0.906036,-0.529035,-0.088934,1.268609,-0.781602,-1.683818,-0.601531,-0.102477,-0.285504,...,Y,Ex,MnPrv,Shed,WD,Normal,1.0,0.0,0.0,1.0
4,-0.866764,0.830872,0.205338,2.105599,-0.524174,1.175195,1.114724,-0.195765,1.255193,-0.285504,...,Y,Ex,MnPrv,Shed,WD,Normal,1.0,0.0,0.0,1.0

In [382]:
from sklearn.preprocessing import OneHotEncoder
onehot = OneHotEncoder(handle_unknown='ignore')
multi_cat = [i for i in categorical_features if i not in bin_cols]
X_train_encoded = pd.DataFrame(onehot.fit_transform(X_train[multi_cat]).toarray(), columns=onehot.get_feature_names_out())
X_train.drop(labels = multi_cat, axis = 1, inplace = True)
X_train = pd.concat([X_train, X_train_encoded],axis = 1)
X_train.head()

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,-0.866764,-0.015314,-0.212896,-0.820445,0.372217,-0.455469,-1.346063,-0.601531,1.037269,-0.285504,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.07411,-0.505211,-0.265245,-0.088934,1.268609,0.718609,0.439214,-0.601531,-0.971996,-0.285504,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
2,-0.631546,-0.148922,-0.177841,-0.820445,1.268609,-1.988293,-1.683818,-0.601531,-0.971996,-0.285504,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
3,-0.161109,-0.460675,-0.324474,-0.820445,1.268609,-1.107734,-1.683818,0.859229,0.267995,-0.285504,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
4,-0.161109,-0.906036,-0.529035,-0.820445,0.372217,-1.531707,-1.683818,-0.601531,-0.49692,-0.285504,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0

In [383]:
X_test_encoded = pd.DataFrame(onehot.transform(X_test[multi_cat]).toarray(), columns=onehot.get_feature_names_out())
X_test.drop(labels = multi_cat, axis = 1, inplace = True)
X_test = pd.concat([X_test, X_test_encoded],axis = 1)
X_test.head()

,MSSubClass,LotFrontage,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,MasVnrArea,BsmtFinSF1,BsmtFinSF2,...,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_Abnorml,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,-0.866764,-0.015314,-0.211594,-0.088934,2.165,-0.259789,0.87347,-0.601531,0.472844,-0.285504,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.07411,1.231697,0.145643,1.374088,-0.524174,0.751222,0.487465,1.496862,1.276986,-0.285504,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
2,-0.631546,-0.638819,-0.160826,-0.820445,0.372217,-1.433867,-1.683818,-0.601531,-0.971996,-0.285504,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
3,-0.161109,-0.906036,-0.529035,-0.088934,1.268609,-0.781602,-1.683818,-0.601531,-0.102477,-0.285504,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
4,-0.866764,0.830872,0.205338,2.105599,-0.524174,1.175195,1.114724,-0.195765,1.255193,-0.285504,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0